### ISSUE TITLE
Error handling: should not show full stack trace

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/ARMClient#4]
For things that are 'normal' user errors and not product bugs, we should try to show a clean simple error message instead of full stack.

e.g. today if I run login command and then cancel, I get:

```
System.AggregateException: One or more errors occurred. ---> Microsoft.IdentityModel.Clients.ActiveDirectory.ActiveDirectoryAuthenticationException: authentication_canceled: Unknown error
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.WindowsFormsWebAuthenticationDialog.ShowBrowser()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.WindowsFormsWebAuthenticationDialog.OnAuthenticate()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.WindowsFormsWebAuthenticationDialogBase.AuthenticateAAD(Uri requestUri, Uri callbackUri)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.InteractiveWebUI.OnAuthenticate()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.WebUI.Authenticate(Uri requestUri, Uri callbackUri)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.OAuth2Request.SendAuthorizeRequest(Authenticator authenticator, String resource, Uri redirectUri, String clientId, String userId, PromptBehavior promptBehavior, String extraQueryParameters, IWebUI webUi)
[truncated, many more stack items]
```

Instead, we should just print `ex.GetBaseException().Message`, which in this case will display:

    authentication_canceled: Unknown error

**Comment by suwatch** [comment]
Fixed by https://github.com/projectkudu/ARMClient/commit/93d3915fdc5b637662d4e6aaaf0df1a2b2fb44b5
